### ISSUE TITLE
"ddd" is a way of working, not a package

### ISSUE THREAD

**Issue by JensRantil** [tlandeka/authentication-microservice-with-domain-driven-design#17]
Just skimmed the source code. I think https://github.com/tlandeka/authentication-microservice-with-domain-driven-design/tree/main/src/main/java/com/tomo/mcauthentication/ddd package probably should be named `domains` - much more clear as DDD really just is a way of working.

**Comment by JensRantil** [comment]
Sounds like a good idea.

**Comment by tlandeka** [comment]
Removed ddd
